name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: ClothingBlueprints
        path: ./Distributable/*
        if-no-files-found: error
